package com.sysrec.projet_ds1_java.Controller;

import com.sysrec.projet_ds1_java.Model.RessourceModel;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.Stage;

import java.time.LocalDateTime;

public class AddResourceController {

    @FXML private TextField titleField;
    @FXML private ComboBox<String> categoryCombo;
    @FXML private TextArea descriptionArea;
    @FXML private ComboBox<String> difficultyCombo;
    @FXML private ComboBox<String> statusComboBox;
    @FXML private TextField keywordsField;

    private TeacherController teacherController;
    private int currentTeacherId;

    public void setTeacherController(TeacherController controller) {
        this.teacherController = controller;
    }

    public void setCurrentTeacherId(int teacherId) {
        this.currentTeacherId = teacherId;
    }

    @FXML
    public void initialize() {
        categoryCombo.getItems().addAll("computer_science", "economic_science");
        difficultyCombo.getItems().addAll("easy", "hard", "medium");
        statusComboBox.getItems().addAll("Private", "Public");
        statusComboBox.setValue("Private");

        categoryCombo.setValue("Computer Science");
        difficultyCombo.setValue("Beginner");
    }

    @FXML
    public void handleSubmit() {
        if (teacherController == null) {
            showAlert("Controller error: TeacherController not set.");
            return;
        }

        String title = titleField.getText().trim();
        String category = categoryCombo.getValue();
        String description = descriptionArea.getText().trim();
        String difficulty = difficultyCombo.getValue();
        String status = statusComboBox.getValue();
        String keywords = keywordsField.getText().trim();

        // Validation
        if (title.isEmpty()) {
            showAlert("Title is required.");
            titleField.requestFocus();
            return;
        }

        if (description.isEmpty()) {
            showAlert("Please add a description.");
            descriptionArea.requestFocus();
            return;
        }

        boolean isPrivate = "Private".equals(status);

        // Create resource with all required fields including initial ratings and student count
        RessourceModel resource = new RessourceModel(
                0, // resourceId (will be generated by database)
                title,
                description,
                difficulty,
                category,
                keywords,
                currentTeacherId,
                false, // isApproved
                isPrivate,
                LocalDateTime.now(), // createdAt
                0, // initial studentCount
                0.0 // initial averageRating
        );

        teacherController.addResource(resource);
        closeWindow();
    }

    private void showAlert(String message) {
        Alert alert = new Alert(Alert.AlertType.WARNING);
        alert.setTitle("Missing Fields");
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    @FXML
    public void handleCancel() {
        closeWindow();
    }

    private void closeWindow() {
        Stage stage = (Stage) titleField.getScene().getWindow();
        stage.close();
    }
}